[package]
name = "sftp_client"
version = "0.1.0"
authors = ["Thomas Andre <thomasandre84@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.8.2"
